### ISSUE TITLE
pplnn failed with CUDA

### ISSUE THREAD

**Issue by Maosquerade** [openppl-public/ppl.nn#8]
I tried CUDA10.2 and CUDA11.0, both failed at 
"[ERROR][2021-07-05 06:38:36.723][buffered_cuda_allocator.cc:91] cuMemAddressReserve failed: operation not supported"
what should I do to avoid this error?

My environment is Centos8 gcc8.4, and the gpu device is Tesla T4. 
BTW the x86 version can run sucessfully.

**Comment by Si-XU** [comment]
CUDA_ERROR_NOT_SUPPORTED = 801
This error indicates that the attempted operation is not supported on the current system or device.

We failed to reproduce this problem.
Perhaps, it because that your GPU device has some extra restrictions.

You can try to reduce total bytes:
Replace buffered_cuda_allocator.cc:86
        addr_len_ = Align(total_bytes_, granularity);
TO 
        addr_len_ = Align(total_bytes_/4, granularity);

**Comment by Maosquerade** [comment]
Thanks for you reply!
It reminds me that my device may have some restrictions. I will try it on another device, thanks again!
